"""
Django settings for cnext_backend project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys

from pathlib import Path
from dotenv import load_dotenv
load_dotenv('.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
root = lambda *x: os.path.join(BASE_DIR, *x)
sys.path.insert(0, root("apps"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-g$rhqtlou5yn8^$)tclvbl5gbb5tf!!jqi(q!&ru5^ldc!os*3'
SECRET_KEY = 'django-insecure-^efs*h@aqke)t)!(qm=ejf9e^_s*min1&!l77@4gky49ro-bv7'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# PROJECT_APPS = ["pdf_generator"]

if not DEBUG:
	INSTALLED_APPS.append('elasticapm.contrib.django')

# INSTALLED_APPS += PROJECT_APPS


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cnext_backend.urls'



# from django_jinja.builtins import DEFAULT_EXTENSIONS


TEMPLATES = [
    # {
    #     "BACKEND": "django_jinja.backend.Jinja2",
    #     "DIRS": [
    #         root("templates"),
    #     ],
    #     "OPTIONS": {
    #         "match_extension": ".jinja",
    #         "context_processors": [
    #             "django.template.context_processors.debug",
    #             "django.template.context_processors.request",
    #             "django.contrib.auth.context_processors.auth",
    #             "django.contrib.messages.context_processors.messages",
    #             "django.contrib.auth.context_processors.auth",
    #             "django.template.context_processors.i18n",
    #             "django.template.context_processors.media",
    #             "django.template.context_processors.static",
    #             "django.template.context_processors.tz",
    #             "django.contrib.messages.context_processors.messages",
     
    #         ],
    #         # "extensions": DEFAULT_EXTENSIONS,
    #     },
    # },
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "APP_DIRS": True,
        "DIRS": [
            root("templates"),
        ],
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.contrib.auth.context_processors.auth",
                "django.template.context_processors.i18n",
                "django.template.context_processors.media",
                "django.template.context_processors.static",
                "django.template.context_processors.tz",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = 'cnext_backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("MASTER_DB_NAME", ""),
        "USER": os.getenv("MASTER_DB_USER", ""),
        "PASSWORD": os.getenv("MASTER_DB_PASSWORD", ""),
        "HOST": os.getenv(
            "MASTER_DB_HOST", "localhost"
        ),  # Empty for localhost through domain sockets or '127.0.0.1' for localhost through TCP.
        "PORT": "3306",  # Set to empty string for default.
        # 'OPTIONS': {'charset': 'utf8mb4'},
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# MEDIA_ROOT = os.path.join("", os.getenv('MEDIA_ROOT'))
# WEB_API_KEY = os.getenv("WEB_API_KEY", "")
